import tkinter as tk
window = tk.Tk()
window.title("RadioButton")
window.geometry("500x500")
import tkinter as tk
def selection():
    label.config(text = "I like" + string.get())
menuBar = tk.Menu(window)
fileMenu = tk.Menu(menuBar, tearoff = False)
fileMenu.add_command(label = "新視窗                                   ⌘N")
fileMenu.add_command(label = "新分頁                                   ⌘T")
fileMenu.add_command(label = "關閉分頁                               ⌘W")
fileMenu.add_command(label = "上傳檔案                               ⌘O")
fileMenu.add_command(label = "列印                                      ⌘P")
fileMenu.add_separator()
fileMenu.add_command(label = "關閉視窗                                   ")
menuBar.add_cascade(label = "檔案", menu = fileMenu)
fileMenu2 = tk.Menu(menuBar, tearoff = False)
fileMenu2.add_command(label = "設定                                    ⌘,")
fileMenu2.add_command(label = "閒置                                    ⌘Q")
subMenu = tk.Menu(menuBar, tearoff = False)
subMenu.add_command(label = "Attack Max")
fileMenu2.add_cascade(label = "進階", menu = subMenu)
menuBar.add_cascade(label = "選項", menu = fileMenu2)
window.config(menu = menuBar)
string = tk.StringVar()
label = tk.Label(window, bg = "#F10", text = "No Choose")
label.pack()
radio1 = tk.Radiobutton(window, text = "I like Python", variable  = string, value = "Python", command = selection)
radio1.pack()
radioa = tk.Radiobutton(window, text = "I like Python Minecraft", variable  = string, value = "哭啊", command = selection)
radioa.pack()

window.mainloop()